# Generated by Django 5.2.4 on 2025-08-18 14:56

import django.db.models.deletion
import mainshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0002_slideritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('afterdiscountprice', models.IntegerField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('coverphoto', models.ImageField(blank=True, null=True, upload_to=mainshop.models.product_cover_upload_path)),
                ('trending', models.BooleanField(default=False)),
                ('newArriable', models.BooleanField(default=False)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainshop.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=mainshop.models.product_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='mainshop.product')),
            ],
        ),
    ]
