# Generated by Django 5.2.4 on 2025-09-15 14:53

import mainshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0003_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=mainshop.models.generate_unique_custom_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('order_products', models.JSONField(default=dict)),
                ('address', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
