# Generated by Django 5.2.4 on 2025-09-17 06:56

import mainshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0005_alter_product_coverphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverphoto',
            field=models.ImageField(blank=True, default='default/product_default.jpeg', upload_to=mainshop.models.product_cover_upload_path),
        ),
    ]
