# Generated by Django 5.2.4 on 2025-10-05 06:42

import mainshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0006_alter_product_coverphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigIntegerField(default=mainshop.models.generate_unique_custom_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
